### ISSUE TITLE
Add getReturn to MixedResult

### ISSUE THREAD

**Issue by Septdir** [webmasterskaya/base-soap-lib#2]
https://github.com/webmasterskaya/base-soap-lib/blob/master/src/Type/MixedResult.php

```

	/**
	 * @return mixed
	 */
	public function getReturn()
	{
		return $this->result;
	}
```

**Comment by kernusr** [comment]
Это частный случай. Лучше выдумать что-то на конкретной реализации, а не в базовой библиотеке
